name: ryankite
favicon: null
layout_spectrum: 0.22667399607598782
typography_spectrum: 0.8919415134005249
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6910758288577199
  lightness: 0.24752330011688173
  saturation: 0.8462336277589202
  rhythmicContrast: 0.4493816460017115
purpose: []
